# Generated by Django 5.0.7 on 2024-08-09 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_details_task_due_date_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.date(2024, 9, 8), help_text='Enter a date in the future', verbose_name='Due Date'),
        ),
    ]
