# Generated by Django 5.0.7 on 2024-08-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='details',
        ),
    ]
